version: '3.9'
services:
  # Next.js Service
  nextjs:
    build:
      context: ./web
      dockerfile: Dockerfile
    container_name: nextjs-c
    ports:
      - "3000:3000"
    restart: unless-stopped
    networks:
      - app-network

  # Nginx Service
  webserver:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    container_name: nginx-c
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    restart: unless-stopped
    volumes:
      - web-root:/var/www/html
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
    depends_on:
      - nextjs
    networks:
      - app-network

  # Certbot Service
  certbot:
    image: certbot/certbot:v2.8.0
    container_name: certbot-c
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - web-root:/var/www/html
    depends_on:
      - webserver
    command: certonly --webroot --webroot-path=/var/www/html --email ${EMAIL} --agree-tos --no-eff-email --staging -d ${DOMAIN}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  certbot-etc:
  certbot-var:
  web-root:
    driver: local
